# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 11:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('match_oligo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_input',
            name='oligo_matches',
            field=models.TextField(default=datetime.datetime(2016, 7, 2, 11, 20, 51, 519408, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
