# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_oligo', '0002_user_input_oligo_matches'),
    ]

    operations = [
        migrations.CreateModel(
            name='oligo_matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user_input',
            name='oligo_matches',
        ),
    ]
