# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20160603_1022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='name',
            name='comments_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='name',
            name='email',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
