# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match_oligo', '0003_auto_20160702_0627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oligo_matches',
        ),
    ]
