# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='comments_text',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='name',
            new_name='name_text',
        ),
    ]
